### ISSUE TITLE
Issue about FFN distribution file.

### ISSUE THREAD

**Issue by Vermouth7** [zijian678/FreeCtrl#1]
Hello, thanks for your contributions, I'm interested in your work. I was executing the code and realized that I could not read the control_probs.pt file correctly. The message that reports the error is as follows:

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

I tried to download the file from a different machine and place it in the correct path, but it still fails. I'm wondering if the original file on google drive is having problems uploading causing the file to be incomplete.

**Comment by zijian678** [comment]
Hi,
Thank you for your interest in our work. We apologize for the corrupted file. 

We have fixed this issue. Now you may download the file using the new link or the download_file.py
